spring.application.name=ping-reportEntity-app
python.service.url=http://localhost:8000
pdf.static.path=file:///D:/SOS%20Infotech/ping-reportEntity-app/src/main/resources/static/
spring.data.mongodb.uri=${MONGO_URI}